In [50]:
# Read list.txt as an array of strings (one per line)
with open('data/in/logger_data/list.txt', 'r') as f:
    file_list = [line.strip() for line in f.readlines()]
file_list = file_list[:-1]
print(file_list)

['2024.12.16', '2024.12.17', '2024.12.18', '2024.12.19', '2024.12.20', '2024.12.21', '2024.12.22', '2024.12.23', '2024.12.24', '2024.12.25', '2024.12.26', '2024.12.27', '2024.12.28', '2024.12.30', '2025.01.03', '2025.01.04', '2025.01.05', '2025.01.07', '2025.01.08', '2025.01.09', '2025.01.11', '2025.01.20', '2025.01.21', '2025.01.23', '2025.01.24', '2025.01.26', '2025.01.27', '2025.01.28', '2025.01.29', '2025.01.30', '2025.01.31', '2025.02.01', '2025.02.02', '2025.02.04', '2025.02.05', '2025.02.07', '2025.02.08', '2025.02.10', '2025.02.11', '2025.02.12', '2025.02.13']


In [51]:
len(file_list)

41

In [ ]:
!ls data/in/oil_protokol/

oil_lab_protokol.csv  oil_lab_zamena_masla.csv


In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/in/oil_protokol/oil_lab_protokol.csv', sep=';', decimal=',')
df.head()

N        date   time     odo  interval_odo  experiment_odo      1      2  \
0  0.0  2024-12-16  14:00  3270.0           0.0             0.0  84.07  13.66   
1  1.0  2024-12-18  12:26  3772.0         502.0           502.0  81.02  13.35   
2  2.0  2024-12-18  17:07  4301.0         529.0          1031.0  76.89  12.99   
3  3.0  2024-12-19  14:06  4801.0         500.0          1531.0  72.10  12.60   
4  4.0  2024-12-20  19:40  5274.0         473.0          2004.0  70.59  12.18   

       3     4  ...   22   23   24   25   26   27      28    29   30   31  
0  166.0  5.69  ...  0.0  0.0  0.0  3.0  0.0  0.0  1163.0  56.0  0.0  0.0  
1  168.0  5.65  ...  0.0  0.0  0.0  5.0  0.0  0.0  1126.0  53.0  0.0  0.0  
2  171.0  5.60  ...  0.0  0.0  0.0  4.0  0.0  0.0  1129.0  51.0  0.0  0.0  
3  176.0  5.53  ...  0.0  0.0  0.0  7.0  0.0  0.0  1113.0  51.0  0.0  0.0  
4  171.0  5.52  ...  0.0  0.0  0.0  7.0  0.0  0.0  1114.0  54.0  0.0  0.0  

[5 rows x 37 columns]

In [27]:
# Display basic info about the dataframe
print(df.info())

# Show the first few rows
display(df.head())

# Show summary statistics for numeric columns
display(df.describe())

# Show unique values for each column (helpful for categorical data)
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique()[:10])  # Show up to 10 unique values
    print('-' * 40)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 37 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   N               18 non-null     float64
 1   date            18 non-null     object 
 2   time            18 non-null     object 
 3   odo             18 non-null     float64
 4   interval_odo    18 non-null     float64
 5   experiment_odo  18 non-null     float64
 6   1               18 non-null     float64
 7   2               18 non-null     float64
 8   3               18 non-null     float64
 9   4               18 non-null     float64
 10  5               18 non-null     float64
 11  6               18 non-null     float64
 12  7               18 non-null     float64
 13  8               18 non-null     float64
 14  9               18 non-null     float64
 15  10              18 non-null     float64
 16  11              18 non-null     float64
 17  12              18 non-null     float

N        date   time     odo  interval_odo  experiment_odo      1      2  \
0  0.0  2024-12-16  14:00  3270.0           0.0             0.0  84.07  13.66   
1  1.0  2024-12-18  12:26  3772.0         502.0           502.0  81.02  13.35   
2  2.0  2024-12-18  17:07  4301.0         529.0          1031.0  76.89  12.99   
3  3.0  2024-12-19  14:06  4801.0         500.0          1531.0  72.10  12.60   
4  4.0  2024-12-20  19:40  5274.0         473.0          2004.0  70.59  12.18   

       3     4  ...   22   23   24   25   26   27      28    29   30   31  
0  166.0  5.69  ...  0.0  0.0  0.0  3.0  0.0  0.0  1163.0  56.0  0.0  0.0  
1  168.0  5.65  ...  0.0  0.0  0.0  5.0  0.0  0.0  1126.0  53.0  0.0  0.0  
2  171.0  5.60  ...  0.0  0.0  0.0  4.0  0.0  0.0  1129.0  51.0  0.0  0.0  
3  176.0  5.53  ...  0.0  0.0  0.0  7.0  0.0  0.0  1113.0  51.0  0.0  0.0  
4  171.0  5.52  ...  0.0  0.0  0.0  7.0  0.0  0.0  1114.0  54.0  0.0  0.0  

[5 rows x 37 columns]

N           odo  interval_odo  experiment_odo          1  \
count  18.000000     18.000000     18.000000       18.000000  18.000000   
mean    8.500000   7434.611111    454.888889     4164.611111  73.315556   
std     5.338539   2543.525602    167.651210     2543.525602   5.730653   
min     0.000000   3270.000000      0.000000        0.000000  67.200000   
25%     4.250000   5400.250000    485.500000     2130.250000  69.107500   
50%     8.500000   7586.000000    503.000000     4316.000000  70.805000   
75%    12.750000   9254.000000    522.750000     5984.000000  76.665000   
max    17.000000  11458.000000    589.000000     8188.000000  84.740000   

               2           3          4          5          6  ...    22  \
count  18.000000   18.000000  18.000000  18.000000  18.000000  ...  18.0   
mean   12.206667  164.555556   5.542222   0.444444   0.561111  ...   0.0   
std     0.933249    7.294012   0.123505   0.046174   0.144462  ...   0.0   
min    10.910000  152.000000   5.330000   0.380000   0.310000  ...   0.0   
25%    11.385000  159.000000   5.457500   0.400000   0.462500  ...   0.0   
50%    12.165000  166.500000   5.535000   0.450000   0.575000  ...   0.0   
75%    12.915000  169.750000   5.647500   0.487500   0.645000  ...   0.0   
max    13.760000  176.000000   5.720000   0.510000   0.860000  ...   0.0   

         23    24         25    26    27           28         29    30    31  
count  18.0  18.0  18.000000  18.0  18.0    18.000000  18.000000  18.0  18.0  
mean    0.0   0.0   5.888889   0.0   0.0  1075.944444  53.555556   0.0   0.0  
std     0.0   0.0   3.197221   0.0   0.0    75.557903   1.616904   0.0   0.0  
min     0.0   0.0   1.000000   0.0   0.0   973.000000  51.000000   0.0   0.0  
25%     0.0   0.0   2.250000   0.0   0.0   987.750000  52.250000   0.0   0.0  
50%     0.0   0.0   7.000000   0.0   0.0  1113.500000  53.000000   0.0   0.0  
75%     0.0   0.0   9.000000   0.0   0.0  1135.000000  55.000000   0.0   0.0  
max     0.0   0.0  10.000000   0.0   0.0  1163.000000  56.000000   0.0   0.0  

[8 rows x 35 columns]

Column: N
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
----------------------------------------
Column: date
['2024-12-16' '2024-12-18' '2024-12-19' '2024-12-20' '2024-12-21'
 '2024-12-22' '2024-12-23' '2024-12-24' '2024-12-27' '2025-01-08']
----------------------------------------
Column: time
['14:00' '12:26' '17:07' '14:06' '19:40' '00:30' '01:00' '07:00' '13:26'
 '13:42']
----------------------------------------
Column: odo
[3270. 3772. 4301. 4801. 5274. 5779. 6272. 6795. 7317. 7855.]
----------------------------------------
Column: interval_odo
[  0. 502. 529. 500. 473. 505. 493. 523. 522. 538.]
----------------------------------------
Column: experiment_odo
[   0.  502. 1031. 1531. 2004. 2509. 3002. 3525. 4047. 4585.]
----------------------------------------
Column: 1
[84.07 81.02 76.89 72.1  70.59 69.93 69.49 68.98 68.61 68.3 ]
----------------------------------------
Column: 2
[13.66 13.35 12.99 12.6  12.18 11.86 11.58 11.32 11.13 11.05]
----------------------------------------
Column: 3
[1

In [28]:
# Drop columns where all values are zero
df = df.dropna(axis=0, how='all')
df = df.loc[:, ~(df == 0).all()]
display(df.head())

N        date   time     odo  interval_odo  experiment_odo      1      2  \
0  0.0  2024-12-16  14:00  3270.0           0.0             0.0  84.07  13.66   
1  1.0  2024-12-18  12:26  3772.0         502.0           502.0  81.02  13.35   
2  2.0  2024-12-18  17:07  4301.0         529.0          1031.0  76.89  12.99   
3  3.0  2024-12-19  14:06  4801.0         500.0          1531.0  72.10  12.60   
4  4.0  2024-12-20  19:40  5274.0         473.0          2004.0  70.59  12.18   

       3     4  ...     8    10     11    12     17      18      20   25  \
0  166.0  5.69  ...  3.82  0.08   48.0  13.6  923.0  2339.0  1962.0  3.0   
1  168.0  5.65  ...  4.70  0.06   82.0  14.1  911.0  2373.0  1927.0  5.0   
2  171.0  5.60  ...  5.20  0.10  133.0  14.3  877.0  2419.0  1889.0  4.0   
3  176.0  5.53  ...  5.60  0.10  145.0  14.9  893.0  2446.0  1856.0  7.0   
4  171.0  5.52  ...  5.80  0.07  145.0  15.2  866.0  2467.0  1843.0  7.0   

       28    29  
0  1163.0  56.0  
1  1126.0  53.0  
2  1129.0  51.0  
3  1113.0  51.0  
4  1114.0  54.0  

[5 rows x 23 columns]

In [ ]:
df['interval_odo'].sum() + 3270

np.float64(11458.0)

In [38]:
df['odo'].iloc[-1]

np.float64(11458.0)

In [ ]:
df.describe()

N           odo  interval_odo  experiment_odo          1  \
count  18.000000     18.000000     18.000000       18.000000  18.000000   
mean    8.500000   7434.611111    454.888889     4164.611111  73.315556   
std     5.338539   2543.525602    167.651210     2543.525602   5.730653   
min     0.000000   3270.000000      0.000000        0.000000  67.200000   
25%     4.250000   5400.250000    485.500000     2130.250000  69.107500   
50%     8.500000   7586.000000    503.000000     4316.000000  70.805000   
75%    12.750000   9254.000000    522.750000     5984.000000  76.665000   
max    17.000000  11458.000000    589.000000     8188.000000  84.740000   

               2           3          4          5          6  ...          8  \
count  18.000000   18.000000  18.000000  18.000000  18.000000  ...  18.000000   
mean   12.206667  164.555556   5.542222   0.444444   0.561111  ...   5.859444   
std     0.933249    7.294012   0.123505   0.046174   0.144462  ...   1.062314   
min    10.910000  152.000000   5.330000   0.380000   0.310000  ...   3.820000   
25%    11.385000  159.000000   5.457500   0.400000   0.462500  ...   5.275000   
50%    12.165000  166.500000   5.535000   0.450000   0.575000  ...   5.950000   
75%    12.915000  169.750000   5.647500   0.487500   0.645000  ...   6.475000   
max    13.760000  176.000000   5.720000   0.510000   0.860000  ...   7.300000   

              10         11         12          17           18           20  \
count  18.000000   18.00000  18.000000   18.000000    18.000000    18.000000   
mean    0.063889  110.00000  15.072222  861.500000  2348.500000  1858.611111   
std     0.026377   41.20394   0.847005   38.012769   181.444936    65.336359   
min     0.020000    5.00000  13.500000  787.000000  1953.000000  1783.000000   
25%     0.050000   85.25000  14.350000  837.750000  2258.000000  1799.250000   
50%     0.065000  120.50000  15.300000  851.500000  2432.500000  1838.000000   
75%     0.087500  142.50000  15.675000  889.000000  2487.500000  1910.750000   
max     0.100000  158.00000  16.200000  924.000000  2517.000000  1985.000000   

              25           28         29  
count  18.000000    18.000000  18.000000  
mean    5.888889  1075.944444  53.555556  
std     3.197221    75.557903   1.616904  
min     1.000000   973.000000  51.000000  
25%     2.250000   987.750000  52.250000  
50%     7.000000  1113.500000  53.000000  
75%     9.000000  1135.000000  55.000000  
max    10.000000  1163.000000  56.000000  

[8 rows x 21 columns]

In [44]:
df['date'].unique()

array(['2024-12-16', '2024-12-18', '2024-12-19', '2024-12-20',
       '2024-12-21', '2024-12-22', '2024-12-23', '2024-12-24',
       '2024-12-27', '2025-01-08', '2025-01-27', '2025-02-04',
       '2025-02-08', '2025-02-11'], dtype=object)

In [43]:
# Example: Search for a specific value in the entire dataframe
value_to_search = 10358  # Replace with your value

result = df.isin([value_to_search])
rows_with_value = df[result.any(axis=1)]
display(rows_with_value)

Empty DataFrame
Columns: [N, date, time, odo, interval_odo, experiment_odo, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 17, 18, 20, 25, 28, 29]
Index: []

[0 rows x 23 columns]